org_name                     = "HelloCloud-7"
workspace_name               = "vault-aws-auth"
vault_addr                   = "https://virgo-vault-cluster-public-vault-9317ff94.8472c6a7.z1.hashicorp.cloud:8200"
vault_namespace              = "admin"
vault_run_role               = "admin-role"
vault_aws_secret_engine_path = "aws-dev"
vault_aws_secret_engine_role = "aws-dev-role"